---
language: ruby
before_install: gem install bundler -v 1.11.2
cache:    bundler
script:   bundle  exec rspec
rvm:
  - '2.2'
  - '2.3.0'
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
